logging:
    level:
        com:
            example: debug
        root: info
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
        cache-enabled: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
server:
    port: 8083
    servlet:
        context-path: /myboot
spring:
    datasource:
        druid:
            stat-view-servlet:
                enabled: true
        dynamic:
            # 配置全局druid参数，请按需配置
            druid:
                initial-size: 5
                max-active: 8
                min-idle: 3
                max-wait: 1000
                validation-query: 'select 1'
            datasource:
                master:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    password: gu425006
                    url: jdbc:mysql://192.168.161.131:3306/mybatis_plus?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
                    username: root
                slave1:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    password: gu425006
                    url: jdbc:mysql://192.168.161.131:3306/mybatis_plus?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
                    username: root
            primary: master #设置默认的数据源或者数据源组,默认值即为master
            strict: true
        type: com.alibaba.druid.pool.DruidDataSource

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params-count: countSq
